// Generated by CoffeeScript 1.3.3
(function() {
  var View;

  View = require('./View');

  View.Collection = require('./CollectionView');

  View.Page = require('./PageView');

  View.Model = require('./ModelView');

  View.Tag = require('./Tag');

  module.exports = View;

}).call(this);
