// Generated by CoffeeScript 1.3.3
(function() {
  var ModelView, View,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  View = require('./View');

  ModelView = (function(_super) {

    __extends(ModelView, _super);

    function ModelView(model) {
      this.model = model;
    }

    return ModelView;

  })(View);

  module.exports = ModelView;

}).call(this);
