// Generated by CoffeeScript 1.3.3
(function() {
  var PageView, Tag, View,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  View = require('./View');

  Tag = require('./Tag');

  PageView = (function(_super) {

    __extends(PageView, _super);

    function PageView(data) {
      this.body = data.body;
      this.route = data.route;
    }

    PageView.prototype.keywords = [];

    PageView.prototype.site_name = "YR PAGE SHOULD HAVE A 'site_name'";

    PageView.prototype.scripts = [];

    PageView.prototype.styles = [];

    PageView.prototype.meta = function(data) {
      var attr, content, html, m, name, opts;
      data = {
        name: {
          description: data.description,
          keywords: "" + (this.keywords.concat(data.keywords).join(', ')),
          viewport: this.viewport || 'width=device-width, initial-scale=1'
        },
        itemprop: {
          name: data.title,
          description: data.description,
          image: data.image,
          url: data.url
        },
        property: {
          "og:title": data.title,
          "og:description": data.description,
          "og:image": data.image,
          "og:type": data.type || 'website',
          "og:url": data.url,
          "og:site_name": data.site_name || data.title
        }
      };
      html = '';
      for (attr in data) {
        m = data[attr];
        for (name in m) {
          content = m[name];
          opts = {
            content: content
          };
          opts[attr] = name;
          html += Tag.meta(opts) + "\n";
        }
      }
      return html;
    };

    PageView.prototype.template = function() {
      return "YR PAGE SHOULD HAVE A TEMPLATE";
    };

    PageView.prototype.container = function() {
      var href, src;
      return "<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    " + (this.meta(this.body.meta())) + "\n\n    <title>" + (this.body.meta().title || this.site_name) + "</title>\n\n    " + (((function() {
        var _i, _len, _ref, _results;
        _ref = this.styles;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          href = _ref[_i];
          _results.push(Tag.stylesheet({
            href: href
          }));
        }
        return _results;
      }).call(this)).join("\n")) + "\n    \n    " + (((function() {
        var _i, _len, _ref, _results;
        _ref = this.scripts;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          src = _ref[_i];
          _results.push(Tag.script({
            src: src
          }));
        }
        return _results;
      }).call(this)).join("\n")) + "\n    \n    " + (this.head()) + "\n  </head>\n  \n  <body>\n    " + (this.template()) + "\n  </body>\n</html>";
    };

    PageView.prototype.html = function() {
      return this.container();
    };

    return PageView;

  })(View);

  module.exports = PageView;

}).call(this);
