// Generated by CoffeeScript 1.3.3
(function() {
  var View;

  View = (function() {

    function View(data) {
      this.data = data;
    }

    View.prototype.template = function() {
      return '<h1>You should probably define .template on your view</h1>';
    };

    View.prototype.html = function() {
      return this.template();
    };

    View.prototype.json = function() {
      return JSON.stringify(this.data);
    };

    return View;

  })();

  module.exports = View;

}).call(this);
